-- Device heartbeat (v4.88.0). One row per DEVICE: which build is alive where.
--
-- WHY: the log stamp (20260727080000) sees only WRITERS. A device that just
-- reads the scoreboard never reveals its build — and the two questions that
-- matter after a deploy («is anyone besides the maintainer updating?»,
-- «is some device stuck on a stale service worker?») are exactly about the
-- silent ones. The heartbeat is written once per day at boot, and
-- immediately after a version change, by every device that can sync.
--
-- WHY A NEW TABLE AND NOT members: (a) members carries the touch_updated_at
-- trigger and feeds the delta sync — a daily write there would bump rows
-- into every device's next pull (the exact churn 20260727080000 refused);
-- (b) a family-link device has NO member identity at boot, and it is
-- precisely such a device we could not classify today; (c) one person can
-- own several devices — per-member columns would last-writer-wins them.
--
-- PRIVACY (stance of 20260727080000, sharpened): clients can WRITE their
-- row but never READ any. RLS has no select policy, so selects return
-- empty for anon — adoption data is dashboard-only (service role), not a
-- cross-family report for anyone holding the publishable key. Content is
-- the version string, a random device id, family, optional member id and
-- a timestamp — no user agent, no model, nothing IP-adjacent. device_id
-- is generated by the client (uid()+uid()) and lives in localStorage;
-- clearing site data mints a new device, which is the honest reading.
--
-- SAFETY: additive, if-not-exists, replay-safe under the db-migrate rule.
-- Writes are gated by the same per-family write key as every other table
-- (fairli_write_ok, 20260717120000). The SELECT grant exists only so
-- ON CONFLICT DO UPDATE cannot trip over column privileges — RLS without
-- a select policy keeps the table invisible regardless.
--
-- HOW TO READ IT (dashboard → SQL editor):
--
--   -- which builds are alive, per family
--   select family_id, app_version, count(*) as devices,
--          max(last_seen) as last_seen
--     from devices group by 1, 2 order by 1, 4 desc;
--
--   -- stale devices: not on the newest build they could be on
--   select * from devices
--    where app_version < (select max(app_version) from devices)
--    order by last_seen desc;
create table if not exists devices (
  device_id  text primary key,
  family_id  text not null,
  member_id  text,
  app_version text,
  last_seen  timestamptz default now()
);
alter table devices enable row level security;
drop policy if exists "dev_ins" on devices;
create policy "dev_ins" on devices for insert with check (fairli_write_ok(family_id));
drop policy if exists "dev_upd" on devices;
create policy "dev_upd" on devices for update using (fairli_write_ok(family_id));
-- deliberately NO select policy: see PRIVACY above
grant select, insert, update on devices to anon, authenticated;
